version: "3.3"
   
services:
  db:
    container_name: mysqlD
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: prueba
    #volumes:
     # - ./mysql:/var/lib/mysql
  web:
    build: .
    container_name: pythonD
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  
  

